### PR TITLE
Add Turkish Localization

### PR DESCRIPTION
**Pull request by NotAShelf**
I started translating this project, and I'd say I'm 1/8 done so far. However, since Turkish is quite the wonky language, some translations may appear weird to Turkish users. Any contributions are appreciated to this localization in case anyone wants to change the wording in some parts.

### CODE REVIEW

**Comment by NotAShelf** [comment]
some changes really can't be translated 100% accurately to Turkish, in those changes I will be attempting to get the closest meaning to the actual translation.

(e.g `Create as... <user>` can't be translated exactly the same because of where <user> needs to be in basic Turkish sentence structure. Correct translation would be "<user> olarak oluştur" but this does not work out quite well from what I'm imagining the page will look like. That is why I translated it to "Choose a user" )

**Comment by NotAShelf** [comment]
I'm in pain

**Comment by NotAShelf** [comment]
Alright this translation is now officially complete

I've read over it several times to try and ensure there are no lines left untranslated but I'm only human and I might've missed a few (although I think I didn't.) As per Turkish sentnece structure, I have had to make some drastic changes to how some strings are layed out, but regardless, I did my absolute best to preserve context in those strings.

For now this concludes the Turkish localization, but I will continue to review and improve the translation as the development of Hangar processes and we have the actual site up and running at its full extent. Until then, this is final.

**Comment by NotAShelf** [comment]
P.S: I'm not native to Turkish, though I did my best in translating as accurately as possible (and I'm quite confident that the translation is nearly 100% accurate) however I might have made some inaccurate translations here and there so if there are any native Turkish speakers, feel free to suggest improvements.

**Comment by NotAShelf** [comment]
I also made a suggestion for a correction in english localization to fix grammar, which is in [this commit](https://github.com/HangarMC/Hangar/pull/537/commits/71d606623a40ecb4ccbad0469dfd25666b767531)

**Comment by MiniDigger** [comment]
thank you very much, I merged the current state, all further discussion and stuff will take place on crowdin sooooon (tm), which will be way nicer.

**Pull request merged**
