### PR TITLE
feat: add agpl as a license option

### PR DESCRIPTION
**Pull request by lokka30**
This PR aims to add the AGPL license as an option for resources to choose.

To-do:

- [x] Add AGPL SVG [here](https://github.com/lokka30/Hangar/tree/add/AGPL-option/frontend/src/components/logos/licenses). Would like help in doing this 😃 I couldn't find a logo file without the "Free as in Freedom" text. 
- [ ] Test if it works

### CODE REVIEW

**Comment by e-im** [comment]
https://gist.github.com/e-im/f6311cb12c7510cb7612480334dcc64b

**Comment by MiniDigger** [comment]
have you tested this? this will most likely look huge
ill take a look locally after work...

**Comment by lokka30** [comment]
I haven't tested this

**Comment by MiniDigger** [comment]
fixed the typos, missing imports and the color and added the license to the config

please actually test your PRs in the future, else you are just creating more work...

**Pull request merged**
